# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: 'Build and Package'
        image: aoblueshell/dotnet3.1-aws-cli
        script:
          - cd SwaggerAPILambda/src/SwaggerAPILambda
          - dotnet build
          - dotnet publish -c Release
          - cp serverless.yml bin/Release/netcoreapp3.1/publish
        artifacts:
          - SwaggerAPILambda/src/SwaggerAPILambda/bin/**
    - step:
        name: 'Deployment to Beta'
        image: aoblueshell/node-serverless-awscli:v4
        deployment: test
        script:
          - cd SwaggerAPILambda/src/SwaggerAPILambda
          - cd bin/Release/netcoreapp3.1/publish
          - npm i -g serverless@2.31.0
          - serverless --version
          - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
          - serverless deploy -v
